---
title: "Class Objectives"
format: docx
editor: visual
---

## Goals of this document

We will treat this class more like a job. There will not be tests or quizzes. Rather we will have conversations where we discuss how you are doing, and what you could improve on. You will reflect on your work, I will reply and we will discuss your grade from there.

We can discuss amendment of objectives as well, especially your personal objectives.

## Basic objectives

Over the course it is expected you will:

**Technically**

1.  Understand and implement the basic R-Studio -\> GitHub workflow; be able to collaborate using GitHub.
2.  Work in Quarto files; be able to adjust format and make output look nice.
3.  Complete https://swcarpentry.github.io/r-novice-gapminder/index.html
4.  Develop slideshow and website.
5.  Use code to further your own research.

**Communications**

1.  Provide respectful feedback in class and on Slack.
2.  Assist with issues on in class and on Slack.

## Personal objectives

-   All writing in quarto
    -   <div>

        > Reflection 1: I began all of my writing in quarto, and have made progress creating a project file where I can store and share my research. However, I was struggling to figure out how to export the quarto file into a word document, so I have been going in between docs and R with my notes. Not the most efficient, I'd like to figure out how to fix this problem; but also feel like I prefer notes, data, and storing in R rather than the writing itself- so maybe we can revise this goal!

        </div>
-   Explore diagrams and flowcharts in R
    -   https://epirhandbook.com/en/diagrams-and-charts.html
    -   https://mikeyharper.uk/flowcharts-in-r-using-diagrammer
        -   <div>

            > Reflection 1: I haven't made as much progress with my charts and diagrams. I now have data from my professor to work with and really get comfortable creating different charts with. For our next reflection, I'd like to set the goals of having a variety of different charts/ diagrams to look at and share. I think for this reflection it makes sense why I've focused on the bones/ structure of my research in general rather than charts, now that I have more there I'd like to make this my next step.

            </div>
-   Let Randy know if spatial data analysis or other things come up

> Workflow progress: Research website
>
> I think I've made good progress in creating my first website through workflowr. Thus far I've created the site, changed the theme, added personal info, a data chart/ new index item, and a photo of myself. I'd like to work on creating a more usable site moving forward and would like for us to discuss/ outline the goals we have for me to complete with the remainder of class!
>
> 1.  Use data from advisor to create charts
> 2.  Write notes as I go with any progress/ issues (?)
>     1.  Almost use the space as a blog???
> 3.  Anything else?

##Final Reflection:
>In the past month since we have met I have made new charts and worked on getting more comfortable wrangling data into R. As of right now I don't know where I want my website to be versus where its at. I have created charts and new dataframes from my advisors data, and I have a few more charts I'd still like to make (before making them all prettier); but beyond that I'm not sure where to go to make it feel like a complete website I can share. If you have any suggestions before things are due next week that'd be helpful!
>I also feel like I haven't been as focused as I was expecting to be due to the coding challenge, so for unexpected increase in workload I'd say what I have done is good; but I would still like to do more.
>I know you'd like for us to have an overarching goal throughout sharing our website, and I'm not really sure what my goal is just yet... I think once I have real data of my own and am working on my own research it will be easier to use the website/ create updates.
